name: Deploy to 'jayse'

env:
  AZURE_WEBAPP_NAME: ${{secrets.AZURE_API_WEBAPP_NAME}} 
  DOTNET_VERSION: '6.0.x'
  
on:
  push:
    branches:
      - jayse

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: 
      name: jayse
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      - name: Build and Publish
        run: |
          dotnet restore src/api
          dotnet build src/api --configuration Release
          dotnet publish src/api -c Release -o '${{ env.DOTNET_ROOT }}/myapp' 
          
      - name: 'Deploy to Azure'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_API_WEBAPP_PUBLISH_PROFILE  }}
          package: '${{ env.DOTNET_ROOT }}/myapp'
